package com.alhaq.amnshield.ui.theme

import androidx.compose.ui.graphics.Color

// Standard M3 color tokens used for Default fallback
val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)
val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

// --- AmnShield Custom Theme Color Schemes ---

// 1. EMERALD CALM (Pearl Teal & Sage Option - Default)
val EmeraldBg = Color(0xFFF3F1EB)
val EmeraldPrimary = Color(0xFF22604E)
val EmeraldOnPrimary = Color.White
val EmeraldPrimaryContainer = Color(0xFFC7E8DC)
val EmeraldOnPrimaryContainer = Color(0xFF042018)
val EmeraldSecondary = Color(0xFF4C635A)
val EmeraldOnSecondary = Color.White
val EmeraldSecondaryContainer = Color(0xFFCEE8DC)
val EmeraldOnSecondaryContainer = Color(0xFF092018)
val EmeraldTertiary = Color(0xFF3B646F)
val EmeraldOnTertiary = Color.White
val EmeraldTertiaryContainer = Color(0xFFBFE9F6)
val EmeraldOnTertiaryContainer = Color(0xFF001F26)
val EmeraldOnSurface = Color(0xFF161D1A)
val EmeraldTextMuted = Color(0xFF3F4944)
val EmeraldSurface = Color(0xFFF9F7F2)
val EmeraldSurfaceVariant = Color(0xFFDBE5DF)
val EmeraldOutline = Color(0xFF6F7974)
val EmeraldOutlineVariant = Color(0xFFBFC9C3)
val EmeraldSurfaceContainerLowest = Color(0xFFFFFFFF)
val EmeraldSurfaceContainerLow = Color(0xFFF3F0E9)
val EmeraldSurfaceContainer = Color(0xFFEDE9E2)
val EmeraldSurfaceContainerHigh = Color(0xFFE7E3DC)
val EmeraldSurfaceContainerHighest = Color(0xFFE1DDD6)

// 2. SUNSET GLOW (Warm Sand & Terracotta Option)
val SunsetBg = Color(0xFFF8EFE9)
val SunsetPrimary = Color(0xFF904B29)
val SunsetOnPrimary = Color.White
val SunsetPrimaryContainer = Color(0xFFFFDBCF)
val SunsetOnPrimaryContainer = Color(0xFF380C00)
val SunsetSecondary = Color(0xFF765849)
val SunsetOnSecondary = Color.White
val SunsetSecondaryContainer = Color(0xFFFFDBCF)
val SunsetOnSecondaryContainer = Color(0xFF2C160B)
val SunsetTertiary = Color(0xFF665F31)
val SunsetOnTertiary = Color.White
val SunsetTertiaryContainer = Color(0xFFEEE4A9)
val SunsetOnTertiaryContainer = Color(0xFF201C00)
val SunsetOnSurface = Color(0xFF201A17)
val SunsetTextMuted = Color(0xFF52443D)
val SunsetSurface = Color(0xFFFFF8F5)
val SunsetSurfaceVariant = Color(0xFFF4DED5)
val SunsetOutline = Color(0xFF85736B)
val SunsetOutlineVariant = Color(0xFFD7C2B9)
val SunsetSurfaceContainerLowest = Color(0xFFFFFFFF)
val SunsetSurfaceContainerLow = Color(0xFFFDF1EB)
val SunsetSurfaceContainer = Color(0xFFF7EBE4)
val SunsetSurfaceContainerHigh = Color(0xFFF1E5DF)
val SunsetSurfaceContainerHighest = Color(0xFFEBE0D9)

// 3. COSMIC NIGHT (Deep Violet Tech Option - High Contrast & Readability)
val CosmicBg = Color(0xFF110B1E)
val CosmicPrimary = Color(0xFFD0BCFF)
val CosmicOnPrimary = Color(0xFF381E72)
val CosmicPrimaryContainer = Color(0xFF533890)
val CosmicOnPrimaryContainer = Color(0xFFF3EBFF)
val CosmicSecondary = Color(0xFFCCC2DC)
val CosmicOnSecondary = Color(0xFF332D41)
val CosmicSecondaryContainer = Color(0xFF4A4458)
val CosmicOnSecondaryContainer = Color(0xFFE8DEF8)
val CosmicTertiary = Color(0xFFF2B8C8)
val CosmicOnTertiary = Color(0xFF4A2532)
val CosmicTertiaryContainer = Color(0xFF66384B)
val CosmicOnTertiaryContainer = Color(0xFFFFD8E4)
val CosmicOnSurface = Color(0xFFF6F2FF)
val CosmicTextMuted = Color(0xFFD6CBEC)
val CosmicSurface = Color(0xFF1A122B)
val CosmicSurfaceVariant = Color(0xFF2E2247)
val CosmicOutline = Color(0xFFA594C9)
val CosmicOutlineVariant = Color(0xFF564575)
val CosmicSurfaceContainerLowest = Color(0xFF0C0717)
val CosmicSurfaceContainerLow = Color(0xFF160E26)
val CosmicSurfaceContainer = Color(0xFF22173B)
val CosmicSurfaceContainerHigh = Color(0xFF2D1F4D)
val CosmicSurfaceContainerHighest = Color(0xFF3B2A63)
val CosmicError = Color(0xFFFFB4AB)
val CosmicOnError = Color(0xFF690005)
val CosmicErrorContainer = Color(0xFF93000A)
val CosmicOnErrorContainer = Color(0xFFFFDAD6)

